services:
  exchange:
    build:
      dockerfile: Dockerfile_exchange

  app:
     build:
       dockerfile: Dockerfile
     environment:
       - EXCHANGE_URL=exchange:8000
     ports:
       - "9090:9090"
